version: '3.8'
services:
  postgres1:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db1
    ports:
      - "5432:5432"

  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db2
    ports:
      - "5433:5432"